development:
  adapter: postgresql
  database: laq_development
  username: postgres
  password: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  database: loveaquote_test
  username: postgres
  password: postgres
  template: template0
  host: localhost
