development:
  adapter: postgresql
  database: loveaquote_development
  username: postgres
  password: postgres
  host: localhost
  template: template0

test:
  adapter: postgresql
  database: loveaquote_test
  username: postgres
  password: postgres
  template: template0
  host: localhost

production:
  adapter: postgresql
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
